vich_uploader:
    db_driver: orm

    mappings:
        formation:
            uri_prefix: /images/formation
            upload_destination: '%kernel.project_dir%/public/images/formation'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true